development:
  adapter: postgresql
  encoding: unicode
  database: tags_service_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tags_service_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tags_service_production
  pool: 5
  password:
